name: continuous-integration

on:
  pull_request:
    branches:
      - master
jobs:
  # checks the dependencies can be installed
  build:
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # install the dependencies
      - name: Install dependencies
        run: yarn install
      # run code style
      - name: Check Code Style
        run: yarn run lint
