name: continuous-integration

on:
  pull_request:
    branches:
      - master
jobs:
  # checks the dependencies can be installed
  install:
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # install the dependencies
      - name: Install dependencies
        run: yarn install

  code-style:
    needs: install
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
      # run the app-pro cypress tests
      - name: code style
        run: yarn run lint
